const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-case-study-covered-call-completed')||'[]'))};
const $=s=>document.querySelector(s),list=$('#syllabusList');
async function loadData(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');return r.json();}
async function init(){state.data=await loadData();render();loadLesson();$('#markComplete').onclick=completeCurrent;}
function render(){const l=state.data.lessons[0];list.innerHTML=`<section class="syllabus-section"><h3>Module 1: Covered Call Case Study</h3><div class="syllabus-item active ${state.completed.has(1)?'done':''}" data-lesson="1"><span class="lesson-number">1</span><span class="lesson-check">${state.completed.has(1)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small>${esc(l.duration)}</small></div><span class="lesson-symbol">◷</span></div></section>`;updateProgress();}
function loadLesson(){const l=state.data.lessons[0],m=state.data.course.availabilityMessage;$('#lessonTitle').textContent=l.title;$('#lessonMeta').textContent=`Lesson 1 of 1 · ${l.duration}`;$('#availabilityText').textContent=m;$('#aboutTitle').textContent=l.title;$('#aboutText').textContent=m;$('#factLesson').textContent='1 of 1';$('#factDuration').textContent=l.duration;$('#factSection').textContent=l.section;$('#factNext').textContent='Course complete';$('#prevBtn').disabled=true;$('#nextBtn').disabled=true;}
function completeCurrent(){state.completed.add(1);localStorage.setItem('oa-case-study-covered-call-completed',JSON.stringify([...state.completed]));const item=list.querySelector('[data-lesson="1"]');item.classList.add('done');item.querySelector('.lesson-check').textContent='✓';updateProgress();}
function updateProgress(){const done=state.completed.has(1)?1:0;$('#progressText').textContent=`${done} / 1`;$('#percentText').textContent=done?'100% complete':'0% complete';$('#progressBar').style.width=done?'100%':'0%';}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
