const DURATION_CACHE_KEY='oa-level45b-vimeo-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level45b-completed')||'[]')),player:null,durations:{}};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
const curriculumGroups=[{title:"Module 1: Course Introduction",lessons:[1,2,3]},{title:"Module 2: Earnings Volatility Foundations",lessons:[4,5,6,7,8,9,10]},{title:"Module 3: Stock Selection and Trade Planning",lessons:[11,12,13,14]},{title:"Module 4: Credit Spreads and Iron Condors",lessons:[15,16,17,18,19,20,21]},{title:"Module 5: Strangles and Butterfly Structures",lessons:[22,23,24]},{title:"Case Studies and Course Summary",lessons:[25,26]}];
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));if(!seconds)return '';const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
function readDurations(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}function saveDurations(){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(state.durations))}catch(e){}}
function lessonDuration(l){if(l.type!=='video'||!l.vimeoId)return l.duration||'Reading';return state.durations[String(l.vimeoId)]||l.duration||'';}function primarySection(n){for(const g of curriculumGroups)if(g.lessons.includes(n))return g.title;return '';}
async function loadSourceData(){try{const r=await fetch('../course-data-source.b64');if(!r.ok)throw 0;const b64=(await r.text()).trim();const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}catch(e){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');return r.json();}}
async function init(){state.data=await loadSourceData();state.durations=readDurations();const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);hydrateVimeoDurations();$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();if(state.current<state.data.lessons.length)go(1)};}
function renderSyllabus(){list.innerHTML=curriculumGroups.map(g=>{const items=g.lessons.map(n=>state.data.lessons[n-1]).filter(Boolean);return `<section class="syllabus-section"><h3>${esc(g.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''} ${state.current===l.number?'active':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(lessonDuration(l))}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':'▤'}</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress();}
function refreshDurationDisplays(id){if(!id)return;const d=state.durations[String(id)];if(!d)return;document.querySelectorAll(`[data-duration-id="${id}"]`).forEach(el=>el.textContent=d);const l=state.data.lessons[state.current-1];if(l&&String(l.vimeoId)===String(id)){$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d;}}
async function hydrateVimeoDurations(){await Promise.allSettled(state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId).map(async l=>{const id=String(l.vimeoId);if(state.durations[id]){refreshDurationDisplays(id);return}try{const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+id)}`);if(!r.ok)return;const j=await r.json();const d=fmtDuration(j.duration);if(d){state.durations[id]=d;saveDurations();refreshDurationDisplays(id)}}catch(e){}}));}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();const displayDuration=lessonDuration(l);$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':'Text lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${displayDuration}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=displayDuration;$('#factSection').textContent=primarySection(l.number);$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video'||!l.vimeoId;if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.ready().then(()=>state.player.getDuration()).then(seconds=>{const d=fmtDuration(seconds);if(d){state.durations[String(l.vimeoId)]=d;saveDurations();refreshDurationDisplays(l.vimeoId)}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}else{nonVideoCard.hidden=false;nonVideoCard.classList.add('text-lesson-card');if(l.content)nonVideoCard.innerHTML=`<article class="text-lesson-content">${l.content}</article>`;else nonVideoCard.innerHTML=`<div class="non-video-icon">✓</div><h2>${esc(l.title)}</h2><p>Review this lesson and mark it complete when ready.</p>`;$('#aboutText').textContent='Read the lesson, then mark it complete when you are ready to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`);}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src='';}function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level45b-completed',JSON.stringify([...state.completed]));list.querySelectorAll(`[data-lesson="${state.current}"]`).forEach(item=>{item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'});updateProgress();}function updateProgress(){const total=state.data?.lessons.length||26,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`;}function go(d){const t=state.current+d;if(t>=1&&t<=state.data.lessons.length)loadLesson(t,true);}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
