const DURATION_CACHE_KEY='oa-level1-vimeo-durations';
function readDurationCache(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function saveDurationCache(cache){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(cache))}catch(e){}}
function fmtDuration(seconds){const s=Math.max(0,Math.round(Number(seconds)||0));if(!s)return '';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderCurriculum(data){const curriculum=document.querySelector('.curriculum-list');if(!curriculum)return;const groups=new Map();data.lessons.forEach(l=>{if(!groups.has(l.section))groups.set(l.section,[]);groups.get(l.section).push(l)});curriculum.innerHTML=[...groups.entries()].map(([section,items])=>`<section class="curriculum-group"><h3 class="curriculum-group-title">${esc(section)}</h3>${items.map(l=>`<a class="curriculum-item" id="lesson-${l.number}" href="player/?lesson=${l.number}"><span class="lesson-index">${l.number}</span><span class="lesson-icon">${l.type==='quiz'?'?':l.type==='text'?'▤':'▶'}</span><div><strong>${esc(l.title)}</strong><small>${esc(l.duration)}</small></div><span class="lesson-arrow">›</span></a>`).join('')}</section>`).join('')}
async function hydrateVimeoDurations(data){const cache=readDurationCache();const videos=data.lessons.filter(l=>l.type==='video'&&l.vimeoId);await Promise.allSettled(videos.map(async l=>{const id=String(l.vimeoId);if(cache[id]){l.duration=cache[id];return}const res=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${id}`)}`);if(!res.ok)return;const info=await res.json();const duration=fmtDuration(info.duration);if(duration){cache[id]=duration;l.duration=duration}}));saveDurationCache(cache)}
async function initLevel1(){const res=await fetch('course-data.json');if(!res.ok)throw new Error(`Failed to load course data: ${res.status}`);const data=await res.json();const cache=readDurationCache();data.lessons.forEach(l=>{if(l.vimeoId&&cache[String(l.vimeoId)])l.duration=cache[String(l.vimeoId)]});renderCurriculum(data);const count=document.querySelector('.curriculum-title strong');if(count)count.textContent=`${data.lessons.length} Lessons`;const mainCourseImage=document.querySelector('.course-image-wrap img');if(mainCourseImage){mainCourseImage.src='../../assets/images/courses/legacy/options-trading-course-level-1-buying-call-option.png';mainCourseImage.style.display='';mainCourseImage.parentElement.classList.remove('image-missing')}const previewWrap=document.querySelector('.course-image-wrap');if(previewWrap){previewWrap.classList.add('course-preview-video');previewWrap.setAttribute('data-vimeo-id','1017811811');const playButton=document.createElement('button');playButton.type='button';playButton.className='course-preview-play';playButton.setAttribute('aria-label','Play course preview');playButton.innerHTML='<span class="course-preview-play-icon">▶</span><span class="course-preview-play-label">Watch course preview</span>';previewWrap.appendChild(playButton);playButton.addEventListener('click',()=>{const vimeoId=previewWrap.dataset.vimeoId;previewWrap.innerHTML=`<iframe class="course-preview-iframe" src="https://player.vimeo.com/video/${vimeoId}?autoplay=1&title=1&byline=1&portrait=1&dnt=1" title="Options Trading Course Level 1 preview" allow="autoplay; fullscreen; picture-in-picture; clipboard-write" allowfullscreen></iframe>`;previewWrap.classList.add('is-playing')})}hydrateVimeoDurations(data).then(()=>renderCurriculum(data))}
initLevel1().catch(console.error);
