const DURATION_KEY='oa-level8-vimeo-durations';
const durations=JSON.parse(localStorage.getItem(DURATION_KEY)||'{}');
function originalSection(n){if(n<=5)return 'Course Introduction';if(n<=13)return 'Chapter 1: Profit and Loss Scenarios in Apple Stock';if(n<=20)return 'Chapter 2: Greeks in Strategy Analysis';if(n<=23)return 'Chapter 3: Bear Call Spread';if(n<=27)return 'Chapter 4: Comparing Greek Advantages';if(n<=41)return 'Chapter 5: Butterfly Scenarios';return 'Chapter 6: Scenarios in the Underlying Asset'}
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function displayDuration(l){const s=l.vimeoId&&durations[String(l.vimeoId)];return s?fmtDuration(s):(l.duration||'—')}
function saveDuration(id,seconds){if(!id||!seconds)return;durations[String(id)]=Number(seconds);localStorage.setItem(DURATION_KEY,JSON.stringify(durations));document.querySelectorAll(`[data-duration-id="${id}"]`).forEach(el=>el.textContent=fmtDuration(seconds))}
async function hydrateDurations(lessons){for(const l of lessons.filter(x=>x.type==='video'&&x.vimeoId)){const id=String(l.vimeoId);if(durations[id]){saveDuration(id,durations[id]);continue}try{const res=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+id)}`);if(!res.ok)continue;const data=await res.json();if(data.duration)saveDuration(id,data.duration)}catch(e){console.debug('Vimeo duration unavailable for',id)}}}
async function initLevel8(){const r=await fetch('course-data.json');if(!r.ok)throw new Error('course data');const d=await r.json(),c=document.querySelector('.curriculum-list');d.lessons.forEach(l=>l.section=originalSection(l.number));if(c){const g=new Map();d.lessons.forEach(l=>{if(!g.has(l.section))g.set(l.section,[]);g.get(l.section).push(l)});c.innerHTML=[...g].map(([s,a])=>`<section class="curriculum-group"><h3 class="curriculum-group-title">${esc(s)}</h3>${a.map(l=>`<a class="curriculum-item" href="player/?lesson=${l.number}"><span class="lesson-index">${l.number}</span><span class="lesson-icon">${l.type==='video'?'▶':'▤'}</span><div><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(displayDuration(l))}</small></div><span class="lesson-arrow">›</span></a>`).join('')}</section>`).join('')}const n=document.querySelector('.curriculum-title strong');if(n)n.textContent=`${d.lessons.length} Lessons`;const w=document.querySelector('.course-image-wrap'),b=document.querySelector('.course-preview-play'),p=d.course.previewVimeoId;if(w&&b&&p)b.onclick=()=>{w.innerHTML=`<iframe class="course-preview-iframe" src="https://player.vimeo.com/video/${p}?autoplay=1&title=0&byline=0&portrait=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`};hydrateDurations(d.lessons)}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
initLevel8().catch(console.error);