const curriculumGroups=[
  {title:'Chapter 1: Delta Fundamentals',lessons:[1,2,3,4,5]},
  {title:'Chapter 2: Delta and the Option Chains',lessons:[6,7,8,9,10,11,12,13]},
  {title:'Chapter 3: Delta in Profit and Loss Analysis',lessons:[14,15,16,17]},
  {title:'Chapter 4: The Delta Curve',lessons:[18,19,20,21,22]},
  {title:'Chapter 4.1: Gamma',lessons:[23,24,25,26,27,28]},
  {title:'Chapter 5: Delta for Hedging an Investment Portfolio',lessons:[29,30,31,32,33,34,35,36,37]},
  {title:'Practical Delta Application',lessons:[38]}
];
const DURATION_CACHE_KEY='oa-level7-vimeo-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level7-completed')||'[]')),player:null,durations:readDurationCache()};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function formatDuration(seconds){seconds=Math.round(Number(seconds)||0);if(!seconds)return '';const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function readDurationCache(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function writeDurationCache(){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(state.durations))}catch(e){}}
async function getVimeoDuration(vimeoId){if(!vimeoId)return '';if(state.durations[vimeoId])return state.durations[vimeoId];try{const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${vimeoId}`)}`);if(!r.ok)return '';const j=await r.json();const d=formatDuration(j.duration);if(d){state.durations[vimeoId]=d;writeDurationCache()}return d}catch(e){return ''}}
async function init(){const r=await fetch('../course-data.json');state.data=await r.json();state.data.lessons.forEach(l=>{if(l.vimeoId&&state.durations[l.vimeoId])l.duration=state.durations[l.vimeoId]});const q=new URLSearchParams(location.search);const requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();go(1)};hydrateDurations()}
function groupTitleForLesson(n){return curriculumGroups.find(g=>g.lessons.includes(n))?.title||state.data.lessons[n-1]?.section||'—'}
function renderSyllabus(){const byNumber=new Map(state.data.lessons.map(l=>[l.number,l]));list.innerHTML=curriculumGroups.map(group=>{const items=group.lessons.map(n=>byNumber.get(n)).filter(Boolean);return `<section class="syllabus-section"><h3>${esc(group.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(l.duration||'—')}</small></div><span class="lesson-symbol">▶</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
async function hydrateDurations(){await Promise.all(state.data.lessons.filter(l=>l.vimeoId&&!state.durations[l.vimeoId]).map(async l=>{const d=await getVimeoDuration(l.vimeoId);if(d){l.duration=d;document.querySelectorAll(`[data-duration-id="${l.vimeoId}"]`).forEach(el=>el.textContent=d);if(state.current===l.number)updateLessonDurationUI(l)}}))}
function updateLessonDurationUI(l){const d=l.duration||'—';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();$('#lessonTitle').textContent=l.title;$('#lessonType').textContent='Video lesson';updateLessonDurationUI(l);$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factSection').textContent=groupTitleForLesson(n);$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=false;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l);if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.getDuration().then(seconds=>{const d=formatDuration(seconds);if(d){state.durations[l.vimeoId]=d;writeDurationCache();l.duration=d;document.querySelectorAll(`[data-duration-id="${l.vimeoId}"]`).forEach(el=>el.textContent=d);if(state.current===l.number)updateLessonDurationUI(l)}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level7-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||0,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
