const DURATION_KEY='oa-level6-vimeo-durations',durationCache=JSON.parse(localStorage.getItem(DURATION_KEY)||'{}');
const groups=[{title:'Course Introduction & Volatility Foundations',from:1,to:7},{title:'Chapter 2: Types of Volatility in Options Trading',from:8,to:13},{title:'Chapter 3: IV Rank vs IV Percentile',from:14,to:19},{title:'Chapter 4–5: Vega and the Option Chains',from:20,to:28},{title:'Chapter 6: The Vega Curve',from:29,to:35},{title:'Chapter 7: Implied Volatility Adjustments',from:36,to:42},{title:'VIX Index & Portfolio Vega',from:43,to:48}];
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level6-completed')||'[]')),player:null};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function sectionFor(n){return groups.find(g=>n>=g.from&&n<=g.to)?.title||'Course Curriculum'}
function fmtDuration(sec){sec=Math.round(Number(sec)||0);if(!sec)return null;const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function durationOf(l){return l.type==='text'?'Reading':(durationCache[l.vimeoId]||l.duration||'—')}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error(`Course data ${r.status}`);state.data=await r.json();state.data.lessons.forEach(l=>l.section=sectionFor(l.number));const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();go(1)};hydrateVimeoDurations()}
function renderSyllabus(){list.innerHTML=groups.map(g=>{const items=state.data.lessons.filter(l=>l.number>=g.from&&l.number<=g.to);return `<section class="syllabus-section"><h3>${esc(g.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small>${esc(durationOf(l))}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':'▤'}</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshCurrentDuration(){const l=state.data.lessons[state.current-1];if(!l)return;const d=durationOf(l);$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d;const el=list.querySelector(`[data-lesson="${l.number}"] small`);if(el)el.textContent=d}
async function hydrateVimeoDurations(){await Promise.all(state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId&&!durationCache[l.vimeoId]).map(async l=>{try{const r=await fetch(`https://vimeo.com/api/oembed.json?url=https://vimeo.com/${encodeURIComponent(l.vimeoId)}`);if(!r.ok)return;const j=await r.json(),d=fmtDuration(j.duration);if(d)durationCache[l.vimeoId]=d}catch(e){}}));localStorage.setItem(DURATION_KEY,JSON.stringify(durationCache));renderSyllabus();refreshCurrentDuration()}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();const d=durationOf(l);$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':'Text lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=d;$('#factSection').textContent=l.section;$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video';if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l)}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;$('#nonVideoText').textContent='Review the lesson resource, then mark it complete to continue.';$('#aboutText').textContent='Review this item and mark it complete to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.getDuration().then(sec=>{const d=fmtDuration(sec);if(d){durationCache[l.vimeoId]=d;localStorage.setItem(DURATION_KEY,JSON.stringify(durationCache));refreshCurrentDuration()}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level6-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||0,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
