const DURATION_CACHE_KEY='oa-level3-vimeo-durations';
function readDurationCache(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function saveDurationCache(cache){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(cache))}catch(e){}}
function fmtDuration(seconds){const s=Math.max(0,Math.round(Number(seconds)||0));if(!s)return '';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
async function hydrateVimeoDurations(data){const cache=readDurationCache();const videos=data.lessons.filter(l=>l.type==='video'&&l.vimeoId);await Promise.allSettled(videos.map(async l=>{const id=String(l.vimeoId);if(cache[id]){l.duration=cache[id];return}const res=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${id}`)}`);if(!res.ok)return;const info=await res.json();const duration=fmtDuration(info.duration);if(duration){cache[id]=duration;l.duration=duration}}));saveDurationCache(cache)}
function renderCurriculum(data){const curriculum=document.querySelector('.curriculum-list');if(!curriculum)return;const groups=new Map();data.lessons.forEach(l=>{if(!groups.has(l.section))groups.set(l.section,[]);groups.get(l.section).push(l)});curriculum.innerHTML=[...groups.entries()].map(([section,items])=>`<section class="curriculum-group"><h3 class="curriculum-group-title">${esc(section)}</h3>${items.map(l=>`<a class="curriculum-item" href="player/?lesson=${l.number}"><span class="lesson-index">${l.number}</span><span class="lesson-icon">${l.type==='video'?'▶':l.type==='quiz'?'?':'▤'}</span><div><strong>${esc(l.title)}</strong><small>${esc(l.duration)}</small></div><span class="lesson-arrow">›</span></a>`).join('')}</section>`).join('')}
async function initLevel3(){const res=await fetch('course-data.json');if(!res.ok)throw new Error(`Failed to load course data: ${res.status}`);const data=await res.json();const cache=readDurationCache();data.lessons.forEach(l=>{if(l.vimeoId&&cache[String(l.vimeoId)])l.duration=cache[String(l.vimeoId)]});renderCurriculum(data);const count=document.querySelector('.curriculum-title strong');if(count)count.textContent=`${data.lessons.length} Lessons`;const note=document.querySelector('.sidebar-note p');if(note)note.textContent=`All ${data.lessons.length} course items are available in the course player. Progress is saved in this browser.`;const wrap=document.querySelector('.course-image-wrap'),btn=document.querySelector('.course-preview-play');const preview=data.course.previewVimeoId||data.lessons.find(l=>l.vimeoId)?.vimeoId;if(wrap&&btn&&preview)btn.addEventListener('click',()=>{wrap.classList.add('is-playing');wrap.innerHTML=`<iframe class="course-preview-iframe" src="https://player.vimeo.com/video/${preview}?autoplay=1&title=0&byline=0&portrait=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Course preview"></iframe>`});hydrateVimeoDurations(data).then(()=>renderCurriculum(data))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
initLevel3().catch(console.error);
