const DURATION_CACHE_KEY='oa-level12-vimeo-durations';
const curriculumGroups=[
 {title:'Butterfly Foundations',lessons:[1,2,3,4,5]},
 {title:'Different Types of Butterfly Spread',lessons:[6,7,8,9]},
 {title:'Vega & Implied Volatility',lessons:[10,11,12,13]},
 {title:'Theta & Time Decay',lessons:[14,15,16,17]},
 {title:'Delta & the Butterfly Strategy',lessons:[18,19,20,21,22]},
 {title:'Butterfly Scenarios',lessons:[23,24,25,26,27,28,29,30,31,32,33,34,35,36]},
 {title:'Trade Execution',lessons:[37]},
 {title:'Position Management & Adjustments',lessons:[38,39,40,41,42,43,44,45,46,47,48,49]},
 {title:'Course Summary',lessons:[50]}
];
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level12-completed')||'[]')),player:null,durations:{}};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function readDurations(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function saveDurations(){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(state.durations))}catch(e){}}
function fmtDuration(seconds){const s=Math.max(0,Math.round(Number(seconds)||0));if(!s)return '';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
function applyGroups(){const byNo=new Map(state.data.lessons.map(l=>[l.number,l]));curriculumGroups.forEach(g=>g.lessons.forEach(n=>{const l=byNo.get(n);if(l)l.section=g.title}))}
function applyCachedDurations(){state.durations=readDurations();state.data.lessons.forEach(l=>{if(l.vimeoId&&state.durations[String(l.vimeoId)])l.duration=state.durations[String(l.vimeoId)]})}
async function hydrateVimeoDurations(){await Promise.allSettled(state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId).map(async l=>{const id=String(l.vimeoId);if(state.durations[id]){l.duration=state.durations[id];return}const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${id}`)}`);if(!r.ok)return;const j=await r.json(),d=fmtDuration(j.duration);if(d){state.durations[id]=d;l.duration=d}}));saveDurations();renderSyllabus();refreshCurrentMeta()}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');state.data=await r.json();applyGroups();applyCachedDurations();const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();if(state.current<state.data.lessons.length)go(1)};hydrateVimeoDurations()}
function renderSyllabus(){const byNo=new Map(state.data.lessons.map(l=>[l.number,l]));list.innerHTML=curriculumGroups.map(g=>{const items=g.lessons.map(n=>byNo.get(n)).filter(Boolean);return `<section class="syllabus-section"><h3>${esc(g.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''} ${state.current===l.number?'active':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small>${esc(l.duration||'Reading')}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':'▤'}</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshCurrentMeta(){const l=state.data?.lessons[state.current-1];if(!l)return;const d=l.duration||'Reading';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d;const small=list.querySelector(`[data-lesson="${l.number}"] small`);if(small)small.textContent=d}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':'Text lesson';$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factSection').textContent=l.section||'—';$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';refreshCurrentMeta();$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video';if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l)}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;$('#nonVideoText').textContent='Review this lesson and mark it complete when ready.';$('#aboutText').textContent='Review this lesson and mark it complete to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.getDuration().then(seconds=>{const d=fmtDuration(seconds);if(!d)return;state.durations[String(l.vimeoId)]=d;l.duration=d;saveDurations();refreshCurrentMeta()}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level12-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||50,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});