const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level10-completed')||'[]')),player:null,durations:JSON.parse(localStorage.getItem('oa-level10-vimeo-durations')||'{}')};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function originalSection(n){if(n<=5)return 'Module 1: Bear Put Spread Foundations';if(n<=10)return 'Module 2: Contract Selection, Profit/Loss and Greeks';if(n<=15)return 'Module 3: Trade Setup and Execution';if(n<=20)return 'Module 4: Monitoring and Adjustments';if(n<=25)return 'Module 5: Risk Management';if(n<=30)return 'Module 6: Advanced Bear Put Spread Techniques';if(n<=35)return 'Module 7: Real-Life Case Studies';if(n<=40)return 'Module 8: Practice and Trading Plan';return 'Module 9: Trading Psychology and Common Mistakes'}
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function saveDuration(id,seconds){if(!id||!seconds)return;state.durations[String(id)]=Number(seconds);localStorage.setItem('oa-level10-vimeo-durations',JSON.stringify(state.durations))}
function lessonDuration(l){if(!l.vimeoId)return '—';const seconds=state.durations[String(l.vimeoId)];return seconds?fmtDuration(seconds):(l.duration&&l.duration!=='3 min'?l.duration:'—')}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');state.data=await r.json();state.data.lessons.forEach(l=>{l.section=originalSection(l.number);l.type='video'});const q=new URLSearchParams(location.search);const requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);hydrateVimeoDurations();$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();if(state.current<state.data.lessons.length)go(1)}}
function renderSyllabus(){const grouped=new Map();state.data.lessons.forEach(l=>{if(!grouped.has(l.section))grouped.set(l.section,[]);grouped.get(l.section).push(l)});list.innerHTML=[...grouped.entries()].map(([section,items])=>`<section class="syllabus-section"><h3>${esc(section)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(lessonDuration(l))}</small></div><span class="lesson-symbol">▶</span></div>`).join('')}</section>`).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshDurationDisplays(id){document.querySelectorAll(`[data-duration-id="${id}"]`).forEach(el=>el.textContent=fmtDuration(state.durations[String(id)]));const l=state.data.lessons[state.current-1];if(l&&String(l.vimeoId)===String(id)){const d=lessonDuration(l);$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d}}
async function hydrateVimeoDurations(){for(const l of state.data.lessons.filter(l=>l.vimeoId)){const id=String(l.vimeoId);if(state.durations[id]){refreshDurationDisplays(id);continue}try{const res=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+id)}`);if(!res.ok)continue;const data=await res.json();if(data.duration){saveDuration(id,data.duration);refreshDurationDisplays(id)}}catch(e){console.debug('Vimeo duration unavailable for',id)}}}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();const d=lessonDuration(l);$('#lessonTitle').textContent=l.title;$('#lessonType').textContent='Video lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=d;$('#factSection').textContent=l.section;$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=!l.vimeoId;if(l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l)}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;$('#nonVideoText').textContent='This is a video lesson, but its Vimeo ID is not present in the original course export.';$('#aboutText').textContent='The lesson is preserved as a video lesson. Its exact Vimeo video cannot be identified safely without the original Vimeo ID.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.ready().then(()=>state.player.getDuration()).then(seconds=>{if(seconds){saveDuration(l.vimeoId,seconds);refreshDurationDisplays(l.vimeoId)}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}if(frame)frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level10-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||43,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=Math.round(done/total*100);$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});