const DURATION_CACHE_KEY='oa-level3-vimeo-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level3-completed')||'[]')),player:null};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function readDurationCache(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function saveDurationCache(cache){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(cache))}catch(e){}}
function fmtDuration(seconds){const s=Math.max(0,Math.round(Number(seconds)||0));if(!s)return '';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
function applyCachedDurations(){const cache=readDurationCache();state.data.lessons.forEach(l=>{if(l.vimeoId&&cache[String(l.vimeoId)])l.duration=cache[String(l.vimeoId)]})}
async function hydrateVimeoDurations(){const cache=readDurationCache();const videos=state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId);await Promise.allSettled(videos.map(async l=>{const id=String(l.vimeoId);if(cache[id]){l.duration=cache[id];return}const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${id}`)}`);if(!r.ok)return;const info=await r.json();const duration=fmtDuration(info.duration);if(duration){cache[id]=duration;l.duration=duration}}));saveDurationCache(cache);renderSyllabus();refreshCurrentMeta()}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error(`Failed to load course data: ${r.status}`);state.data=await r.json();applyCachedDurations();const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();go(1)};hydrateVimeoDurations()}
function renderSyllabus(){const grouped=new Map();state.data.lessons.forEach(l=>{if(!grouped.has(l.section))grouped.set(l.section,[]);grouped.get(l.section).push(l)});list.innerHTML=[...grouped.entries()].map(([section,items])=>`<section class="syllabus-section"><h3>${esc(section)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''} ${state.current===l.number?'active':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small>${esc(l.duration)}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':l.type==='quiz'?'?':'▤'}</span></div>`).join('')}</section>`).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshCurrentMeta(){const l=state.data?.lessons[state.current-1];if(!l)return;$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${l.duration}`;$('#factDuration').textContent=l.duration;const item=list.querySelector(`[data-lesson="${l.number}"] small`);if(item)item.textContent=l.duration}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':l.type==='quiz'?'Knowledge check':'Text lesson';$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factSection').textContent=l.section;$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';refreshCurrentMeta();$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video';if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l)}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;$('#nonVideoText').textContent=l.type==='quiz'?'Complete the knowledge check, then mark it complete to continue.':'Review the lesson material, then mark it complete to continue.';$('#aboutText').textContent='Review this item and mark it complete to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.getDuration().then(seconds=>{const duration=fmtDuration(seconds);if(!duration)return;const cache=readDurationCache();cache[String(l.vimeoId)]=duration;saveDurationCache(cache);l.duration=duration;refreshCurrentMeta();const item=list.querySelector(`[data-lesson="${l.number}"] small`);if(item)item.textContent=duration}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level3-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||0,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
