const DURATION_CACHE_KEY='oa-level22-vimeo-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level22-completed')||'[]')),player:null,durations:{}};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
const curriculumGroups=[
{title:"Module 1: VIX Foundations",lessons:[1,2,3,4,5]},
{title:"Module 2: VIX Products and Analysis",lessons:[6,7,8,9,10]},
{title:"Module 3: VIX Hedging",lessons:[11,12,13,14,15]},
{title:"Module 4: VIX Speculation",lessons:[16,17,18,19,20]},
{title:"Module 5: Market Analysis",lessons:[21,22,23,24,25]},
{title:"Module 6: Advanced Hedging and Adjustments",lessons:[26,27,28,29,30]},
{title:"Module 7: Case Studies",lessons:[31,32,33,34,35]},
{title:"Module 8: Simulated Trades",lessons:[36,37,38,39,40]},
{title:"Module 9: Risk Management System",lessons:[41,42,43,44,45]}
];
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));if(!seconds)return '';const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
function readDurations(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}function saveDurations(){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(state.durations))}catch(e){}}
function lessonDuration(l){return l.vimeoId?(state.durations[String(l.vimeoId)]||l.duration):l.duration;}
async function loadSourceData(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');return r.json();}
async function init(){state.data=await loadSourceData();state.durations=readDurations();const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);hydrateVimeoDuration();$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();if(state.current<state.data.lessons.length)go(1)};}
function renderSyllabus(){list.innerHTML=curriculumGroups.map(g=>{const items=g.lessons.map(n=>state.data.lessons[n-1]).filter(Boolean);return `<section class="syllabus-section"><h3>${esc(g.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''} ${state.current===l.number?'active':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(lessonDuration(l))}</small></div><span class="lesson-symbol">${l.vimeoId?'▶':'◷'}</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress();}
function primarySection(n){for(const g of curriculumGroups)if(g.lessons.includes(n))return g.title;return '';}
function refreshDuration(id){const d=state.durations[String(id)];if(!d)return;document.querySelectorAll(`[data-duration-id="${id}"]`).forEach(el=>el.textContent=d);const l=state.data.lessons[state.current-1];if(l&&String(l.vimeoId)===String(id)){$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d;}}
async function hydrateVimeoDuration(){const l=state.data.lessons.find(x=>x.vimeoId);if(!l)return;const id=String(l.vimeoId);if(state.durations[id]){refreshDuration(id);return}try{const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+id)}`);if(!r.ok)return;const j=await r.json(),d=fmtDuration(j.duration);if(d){state.durations[id]=d;saveDurations();refreshDuration(id)}}catch(e){}}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();const d=lessonDuration(l),message=state.data.course.availabilityMessage;$('#lessonTitle').textContent=l.title;$('#lessonType').textContent='Video lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=d;$('#factSection').textContent=primarySection(l.number);$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=!l.vimeoId;if(l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.ready().then(()=>state.player.getDuration()).then(seconds=>{const value=fmtDuration(seconds);if(value){state.durations[String(l.vimeoId)]=value;saveDurations();refreshDuration(l.vimeoId)}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}else{nonVideoCard.hidden=false;$('#availabilityMessage').textContent=message;$('#aboutText').textContent=message}if(push)history.replaceState(null,'',`?lesson=${n}`);}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src='';}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level22-completed',JSON.stringify([...state.completed]));list.querySelectorAll(`[data-lesson="${state.current}"]`).forEach(item=>{item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'});updateProgress();}
function updateProgress(){const total=state.data?.lessons.length||45,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`;}
function go(d){const t=state.current+d;if(t>=1&&t<=state.data.lessons.length)loadLesson(t,true);}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
