const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level15-completed')||'[]')),player:null,durations:JSON.parse(localStorage.getItem('oa-level15-vimeo-durations')||'{}')};const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function saveDuration(id,seconds){if(!id||!seconds)return;state.durations[String(id)]=Number(seconds);localStorage.setItem('oa-level15-vimeo-durations',JSON.stringify(state.durations))}
function lessonDuration(l){if(l.type!=='video'||!l.vimeoId)return l.duration;const seconds=state.durations[String(l.vimeoId)];return seconds?fmtDuration(seconds):l.duration}
const curriculumGroups=[
  {title:'What will you learn in this course?',lessons:[1,2,3,4,5,6]},
  {title:'Module 2: Market Analysis',lessons:[7,8,9]},
  {title:'The Greeks and Short Straddle',lessons:[10,11,12,13,14,15,16,17,18,19,20,21]},
  {title:'Module 3: Constructing the Short Straddle',lessons:[22,23,24]},
  {title:'Module 4: Managing the Short Straddle',lessons:[25,26,27,28]},
  {title:'Module 5: Risk Management',lessons:[29,30,31,32,33,34]},
  {title:'Module 6: Real-Life Case Studies',lessons:[33]},
  {title:'Module 6.2: Short Straddle Adjustments',lessons:[34]},
  {title:'Module 7: Advanced Strategies',lessons:[35,36,37,38,39,40,41,42]},
  {title:'Module 8: Psychological Aspects',lessons:[43,44,45,46,47]},
  {title:'Module 9: Tools and Resources',lessons:[48,49,50,51,52]},
  {title:'Module 10: Course Summary and Next Steps',lessons:[53,54,55,56,57]}
];
function primarySection(n){for(const g of curriculumGroups){if(g.lessons.includes(n))return g.title}return ''}
async function init(){const r=await fetch('../course-data.json');state.data=await r.json();const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);hydrateVimeoDurations();$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();if(state.current<state.data.lessons.length)go(1)}}
function renderSyllabus(){list.innerHTML=curriculumGroups.map(g=>{const items=g.lessons.map(n=>state.data.lessons[n-1]).filter(Boolean);return `<section class="syllabus-section"><h3>${esc(g.title)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(lessonDuration(l))}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':'▤'}</span></div>`).join('')}</section>`}).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshDurationDisplays(id){const l=state.data.lessons[state.current-1];document.querySelectorAll(`[data-duration-id="${id}"]`).forEach(el=>el.textContent=fmtDuration(state.durations[String(id)]));if(l&&String(l.vimeoId)===String(id)){const d=lessonDuration(l);$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${d}`;$('#factDuration').textContent=d}}
async function hydrateVimeoDurations(){const videos=state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId);for(const l of videos){const id=String(l.vimeoId);if(state.durations[id]){refreshDurationDisplays(id);continue}try{const res=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+id)}`);if(!res.ok)continue;const data=await res.json();if(data.duration){saveDuration(id,data.duration);refreshDurationDisplays(id)}}catch(e){console.debug('Vimeo duration unavailable for',id)}}}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];stopPlayer();const displayDuration=lessonDuration(l);$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':'Text lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${displayDuration}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=displayDuration;$('#factSection').textContent=primarySection(l.number);$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video'||!l.vimeoId;if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.ready().then(()=>state.player.getDuration()).then(seconds=>{if(seconds){saveDuration(l.vimeoId,seconds);refreshDurationDisplays(l.vimeoId)}}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;$('#nonVideoText').textContent='Review this lesson and mark it complete when ready.';$('#aboutText').textContent='Review this lesson and mark it complete to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level15-completed',JSON.stringify([...state.completed]));list.querySelectorAll(`[data-lesson="${state.current}"]`).forEach(item=>{item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'});updateProgress()}function updateProgress(){const total=state.data?.lessons.length||57,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=Math.round(done/total*100);$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}function go(d){const t=state.current+d;if(t>=1&&t<=state.data.lessons.length)loadLesson(t,true)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});