const COMPLETED_KEY='oa-practical-long-put-completed',DURATION_CACHE_KEY='oa-practical-long-put-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem(COMPLETED_KEY)||'[]')),player:null,durations:{}};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),textCard=$('#textCard');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(s){s=Math.max(0,Math.round(Number(s)||0));if(!s)return '';const m=Math.floor(s/60),r=s%60;return `${m}:${String(r).padStart(2,'0')}`}
function groups(){return [...new Set(state.data.lessons.map(l=>l.section))].map(title=>({title,lessons:state.data.lessons.filter(l=>l.section===title)}))}function duration(l){return state.durations[l.vimeoId]||l.duration||'Reading'}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error('course data');state.data=await r.json();try{state.durations=JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){};const requested=Number(new URLSearchParams(location.search).get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);hydrate();$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{complete();if(state.current<state.data.lessons.length)go(1)}}
function renderSyllabus(){list.innerHTML=groups().map(g=>`<section class="syllabus-section"><h3>${esc(g.title)}</h3>${g.lessons.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''} ${state.current===l.number?'active':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small data-duration-id="${l.vimeoId||''}">${esc(duration(l))}</small></div><span class="lesson-symbol">${l.vimeoId?'▶':'◷'}</span></div>`).join('')}</section>`).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));progress()}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];stop();$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.vimeoId?'Video lesson':'Text lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${duration(l)}`;$('#aboutTitle').textContent=l.title;$('#aboutText').textContent=l.vimeoId?'Watch the original lesson video. Completion is saved automatically when the video ends.':'Read the original course introduction, then mark the lesson complete.';$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=duration(l);$('#factSection').textContent=l.section;$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));videoCard.hidden=true;textCard.hidden=true;$('#autoNext').closest('label').hidden=!l.vimeoId;if(l.vimeoId){videoCard.hidden=false;frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.on('ended',()=>{complete();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}else{textCard.hidden=false;textCard.innerHTML=`<h2>${esc(l.title)}</h2>${l.contentHtml||''}`}if(push)history.replaceState(null,'',`?lesson=${n}`)}
async function hydrate(){await Promise.allSettled(state.data.lessons.filter(l=>l.vimeoId&&!state.durations[l.vimeoId]).map(async l=>{const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent('https://vimeo.com/'+l.vimeoId)}`);if(r.ok){const j=await r.json(),v=fmt(j.duration);if(v)state.durations[l.vimeoId]=v}}));try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(state.durations))}catch(e){}renderSyllabus();const l=state.data.lessons[state.current-1];$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${duration(l)}`;$('#factDuration').textContent=duration(l)}
function stop(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}function complete(){state.completed.add(state.current);localStorage.setItem(COMPLETED_KEY,JSON.stringify([...state.completed]));renderSyllabus()}function progress(){const total=state.data?.lessons.length||5,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=Math.round(done/total*100);$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}function go(d){const n=state.current+d;if(n>=1&&n<=state.data.lessons.length)loadLesson(n,true)}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});
