const DURATION_CACHE_KEY='oa-level11-vimeo-durations';
function readDurationCache(){try{return JSON.parse(localStorage.getItem(DURATION_CACHE_KEY)||'{}')}catch(e){return {}}}
function saveDurationCache(cache){try{localStorage.setItem(DURATION_CACHE_KEY,JSON.stringify(cache))}catch(e){}}
function fmtDuration(seconds){const s=Math.max(0,Math.round(Number(seconds)||0));if(!s)return '';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
function renderCurriculum(d){const c=document.querySelector('.curriculum-list');if(!c)return;const g=new Map();d.lessons.forEach(l=>{if(!g.has(l.section))g.set(l.section,[]);g.get(l.section).push(l)});c.innerHTML=[...g].map(([s,a])=>`<section class="curriculum-group"><h3 class="curriculum-group-title">${esc(s)}</h3>${a.map(l=>`<a class="curriculum-item" href="player/?lesson=${l.number}"><span class="lesson-index">${l.number}</span><span class="lesson-icon">${l.type==='video'?'▶':'▤'}</span><div><strong>${esc(l.title)}</strong><small>${esc(l.duration||'Reading')}</small></div><span class="lesson-arrow">›</span></a>`).join('')}</section>`).join('')}
async function hydrateVimeoDurations(d){const cache=readDurationCache();const videos=d.lessons.filter(l=>l.type==='video'&&l.vimeoId);await Promise.allSettled(videos.map(async l=>{const id=String(l.vimeoId);if(cache[id]){l.duration=cache[id];return}const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${id}`)}`);if(!r.ok)return;const info=await r.json();const duration=fmtDuration(info.duration);if(duration){cache[id]=duration;l.duration=duration}}));saveDurationCache(cache);renderCurriculum(d)}
async function initLevel11(){const r=await fetch('course-data.json');if(!r.ok)throw new Error('course data');const d=await r.json();const cache=readDurationCache();d.lessons.forEach(l=>{if(l.vimeoId&&cache[String(l.vimeoId)])l.duration=cache[String(l.vimeoId)]});renderCurriculum(d);const n=document.querySelector('.curriculum-title strong');if(n)n.textContent=`${d.lessons.length} Lessons`;const w=document.querySelector('.course-image-wrap'),b=document.querySelector('.course-preview-play'),p=d.course.previewVimeoId;if(w&&b&&p)b.onclick=()=>{w.innerHTML=`<iframe class="course-preview-iframe" src="https://player.vimeo.com/video/${p}?autoplay=1&title=0&byline=0&portrait=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`};hydrateVimeoDurations(d)}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
initLevel11().catch(console.error);
