const CACHE_KEY='oa-level4-vimeo-durations';
const state={data:null,current:1,completed:new Set(JSON.parse(localStorage.getItem('oa-level4-completed')||'[]')),player:null,durations:loadDurationCache()};
const $=s=>document.querySelector(s),list=$('#syllabusList'),frame=$('#vimeoFrame'),videoCard=$('#videoCard'),nonVideoCard=$('#nonVideoCard');
function loadDurationCache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'{}')}catch{return {}}}
function saveDurationCache(){try{localStorage.setItem(CACHE_KEY,JSON.stringify(state.durations))}catch{}}
function fmtDuration(seconds){seconds=Math.max(0,Math.round(Number(seconds)||0));const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
async function init(){const r=await fetch('../course-data.json');if(!r.ok)throw new Error(`Failed to load course data: ${r.status}`);state.data=await r.json();state.data.lessons.forEach(l=>{if(l.vimeoId&&state.durations[l.vimeoId])l.duration=state.durations[l.vimeoId]});const q=new URLSearchParams(location.search),requested=Number(q.get('lesson'))||1;renderSyllabus();loadLesson(Math.min(Math.max(requested,1),state.data.lessons.length),false);$('#prevBtn').onclick=()=>go(-1);$('#nextBtn').onclick=()=>go(1);$('#markComplete').onclick=()=>{completeCurrent();go(1)};hydrateVimeoDurations()}
function renderSyllabus(){const grouped=new Map();state.data.lessons.forEach(l=>{if(!grouped.has(l.section))grouped.set(l.section,[]);grouped.get(l.section).push(l)});list.innerHTML=[...grouped.entries()].map(([section,items])=>`<section class="syllabus-section"><h3>${esc(section)}</h3>${items.map(l=>`<div class="syllabus-item ${state.completed.has(l.number)?'done':''}" data-lesson="${l.number}"><span class="lesson-number">${l.number}</span><span class="lesson-check">${state.completed.has(l.number)?'✓':''}</span><div class="lesson-copy"><strong>${esc(l.title)}</strong><small>${esc(l.duration)}</small></div><span class="lesson-symbol">${l.type==='video'?'▶':l.type==='quiz'?'?':'▤'}</span></div>`).join('')}</section>`).join('');list.querySelectorAll('.syllabus-item').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson),true));updateProgress()}
function refreshLessonDuration(l){const small=list.querySelector(`[data-lesson="${l.number}"] small`);if(small)small.textContent=l.duration;if(state.current===l.number){$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${l.duration}`;$('#factDuration').textContent=l.duration}}
async function hydrateVimeoDurations(){await Promise.all(state.data.lessons.filter(l=>l.type==='video'&&l.vimeoId&&!state.durations[l.vimeoId]).map(async l=>{try{const r=await fetch(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(`https://vimeo.com/${l.vimeoId}`)}`);if(!r.ok)return;const meta=await r.json();if(meta.duration){l.duration=fmtDuration(meta.duration);state.durations[l.vimeoId]=l.duration;refreshLessonDuration(l)}}catch(e){console.warn('Vimeo duration unavailable',l.vimeoId)}}));saveDurationCache()}
function loadLesson(n,push=true){state.current=n;const l=state.data.lessons[n-1];if(!l)return;stopPlayer();$('#lessonTitle').textContent=l.title;$('#lessonType').textContent=l.type==='video'?'Video lesson':l.type==='quiz'?'Knowledge check':'Text lesson';$('#lessonMeta').textContent=`Lesson ${l.number} of ${state.data.lessons.length} · ${l.duration}`;$('#aboutTitle').textContent=l.title;$('#factLesson').textContent=`${l.number} of ${state.data.lessons.length}`;$('#factDuration').textContent=l.duration;$('#factSection').textContent=l.section;$('#factNext').textContent=state.data.lessons[n]?.title||'Course complete';$('#prevBtn').disabled=n===1;$('#nextBtn').disabled=n===state.data.lessons.length;list.querySelectorAll('.syllabus-item').forEach(el=>el.classList.toggle('active',Number(el.dataset.lesson)===n));const active=list.querySelector(`[data-lesson="${n}"]`);if(active)active.scrollIntoView({block:'nearest'});videoCard.hidden=true;nonVideoCard.hidden=true;$('#autoNext').closest('label').hidden=l.type!=='video';if(l.type==='video'&&l.vimeoId){videoCard.hidden=false;$('#aboutText').textContent='Watch the lesson. When the video ends, it is marked complete automatically.';loadVimeo(l)}else{nonVideoCard.hidden=false;$('#nonVideoTitle').textContent=l.title;if(l.type==='quiz')$('#nonVideoText').textContent='Complete this knowledge check, then mark it complete to continue.';else if(l.type==='video')$('#nonVideoText').textContent='This lesson video is currently unavailable.';else $('#nonVideoText').textContent='Review this lesson and mark it complete to continue.';$('#aboutText').textContent='Review this item and mark it complete to continue.'}if(push)history.replaceState(null,'',`?lesson=${n}`)}
function loadVimeo(l){frame.src=`https://player.vimeo.com/video/${l.vimeoId}?title=0&byline=0&portrait=0&autopause=0`;state.player=new Vimeo.Player(frame);state.player.getDuration().then(seconds=>{if(!seconds)return;l.duration=fmtDuration(seconds);state.durations[l.vimeoId]=l.duration;saveDurationCache();refreshLessonDuration(l)}).catch(()=>{});state.player.on('ended',()=>{completeCurrent();if($('#autoNext').checked&&state.current<state.data.lessons.length)setTimeout(()=>go(1),700)})}
function stopPlayer(){if(state.player){try{state.player.unload()}catch(e){}state.player=null}frame.src=''}
function completeCurrent(){state.completed.add(state.current);localStorage.setItem('oa-level4-completed',JSON.stringify([...state.completed]));const item=list.querySelector(`[data-lesson="${state.current}"]`);if(item){item.classList.add('done');item.querySelector('.lesson-check').textContent='✓'}updateProgress()}
function updateProgress(){const total=state.data?.lessons.length||0,done=[...state.completed].filter(n=>n>=1&&n<=total).length,pct=total?Math.round(done/total*100):0;$('#progressText').textContent=`${done} / ${total}`;$('#percentText').textContent=`${pct}% complete`;$('#progressBar').style.width=`${pct}%`}
function go(d){const t=state.current+d;if(t<1||t>state.data.lessons.length)return;loadLesson(t,true)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init().catch(e=>{console.error(e);$('#lessonTitle').textContent='Could not load course data'});